//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.19 at 02:58:00 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xml.poslovna.bezbednost/ws/MT900", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package bezbednost.poslovna.xml.ws.mt900;
